sidus_template:
    routes:
        index:
            template: 'actions/index.html.twig'
        new_game:
            template: 'actions/new_game.html.twig'
        play:
            template: 'actions/play.html.twig'
        rules:
            template: 'actions/rules.html.twig'
        legal_notice:
            template: 'actions/legal_notice.html.twig'
        terms:
            template: 'actions/terms.html.twig'
        contact:
            template: 'actions/contact.html.twig'
        feedback:
            template: 'actions/feedback.html.twig'
