<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203141243 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE board_position (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, board_position_data BYTEA NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D6DBE74C70C3F7F9 ON board_position (board_position_data)');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, opponent_type_value INT NOT NULL, is_white BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_over_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, white_wins BOOLEAN NOT NULL, draw BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232B318CD17F50A6 ON game (uuid)');
        $this->addSql('CREATE TABLE game_move (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_id INT NOT NULL, move_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42B5B54E48FD905 ON game_move (game_id)');
        $this->addSql('CREATE INDEX IDX_42B5B546DC541A8 ON game_move (move_id)');
        $this->addSql('CREATE TABLE move (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, move_data BYTEA NOT NULL, from_board_position_id BIGINT NOT NULL, to_board_position_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF3E3778EF7D0D7B ON move (from_board_position_id)');
        $this->addSql('CREATE INDEX IDX_EF3E377812A88186 ON move (to_board_position_id)');
        $this->addSql('CREATE UNIQUE INDEX move_unique_idx ON move (move_data, from_board_position_id)');
        $this->addSql('ALTER TABLE game_move ADD CONSTRAINT FK_42B5B54E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_move ADD CONSTRAINT FK_42B5B546DC541A8 FOREIGN KEY (move_id) REFERENCES move (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778EF7D0D7B FOREIGN KEY (from_board_position_id) REFERENCES board_position (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E377812A88186 FOREIGN KEY (to_board_position_id) REFERENCES board_position (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_move DROP CONSTRAINT FK_42B5B54E48FD905');
        $this->addSql('ALTER TABLE game_move DROP CONSTRAINT FK_42B5B546DC541A8');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E3778EF7D0D7B');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E377812A88186');
        $this->addSql('DROP TABLE board_position');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE game_move');
        $this->addSql('DROP TABLE move');
    }
}
