<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 3 (04-matchmaking.md sec 2, 01-domain-model.md sec 6.6): the `seek`
 * table. Column set/names verified against `Seek`'s real Doctrine mapping
 * via `doctrine:migrations:diff` (the auto-generated statements below, hand
 * -trimmed of unrelated pre-existing schema drift bundled into that diff).
 * The partial unique index, three CHECK constraints and the heartbeat
 * fillfactor tuning are added by hand - `migrations:diff` does not
 * regenerate any of those (01-domain-model.md sec 6.6).
 */
final class Version20260728143523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the seek table (04-matchmaking.md sec 2, 01-domain-model.md sec 6.6).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE seek (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              uuid UUID NOT NULL,
              speed_category_value SMALLINT DEFAULT NULL,
              rated BOOLEAN NOT NULL,
              color_preference_value SMALLINT NOT NULL,
              rating_min INT DEFAULT NULL,
              rating_max INT DEFAULT NULL,
              auto_widen BOOLEAN NOT NULL,
              rating_snapshot INT NOT NULL,
              status_value SMALLINT NOT NULL,
              created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              last_heartbeat_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              time_control_kind SMALLINT DEFAULT 0 NOT NULL,
              initial_seconds INT DEFAULT NULL,
              increment_seconds INT DEFAULT NULL,
              days_per_move INT DEFAULT NULL,
              user_id UUID NOT NULL,
              matched_game_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D438FE97D17F50A6 ON seek (uuid)');
        $this->addSql('CREATE INDEX idx_seek_pool ON seek (status_value, speed_category_value, created_at)');
        $this->addSql('CREATE INDEX IDX_D438FE9774037D4D ON seek (matched_game_id)');
        // Deliberately not `IDX_D438FE97A76ED395 ON seek (user_id)` alone -
        // the partial unique index below already serves every `user_id`
        // lookup that matters (open seeks), and doubles as the invariant.
        $this->addSql('CREATE UNIQUE INDEX uniq_seek_open_per_user ON seek (user_id) WHERE status_value = 0');
        $this->addSql(<<<'SQL'
            ALTER TABLE seek
            ADD CONSTRAINT FK_D438FE97A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE seek
            ADD CONSTRAINT FK_D438FE9774037D4D FOREIGN KEY (matched_game_id) REFERENCES game (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE seek ADD CONSTRAINT chk_seek_widen_xor_window
                CHECK (NOT auto_widen OR (rating_min IS NULL AND rating_max IS NULL))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE seek ADD CONSTRAINT chk_seek_window_ordered
                CHECK (rating_min IS NULL OR rating_max IS NULL OR rating_min <= rating_max)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE seek ADD CONSTRAINT chk_seek_rated_needs_clock
                CHECK (NOT rated OR time_control_kind <> 0)
        SQL);
        // Heartbeats are one single-row UPDATE per open seek every 10s
        // (04-matchmaking.md sec 4.3). Leave room on each page for HOT
        // updates, and let autovacuum keep up with the churn.
        $this->addSql('ALTER TABLE seek SET (fillfactor = 70, autovacuum_vacuum_scale_factor = 0.01)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE seek');
    }
}
