<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * In-app notification centre (07-notifications.md sec 7, 01-domain-model.md
 * sec 4.9): the `notification` table. `subject` is an addition to the
 * original spec - it lets a repeat "your turn" collapse into the unread row
 * for the same game, and opening a game mark its rows read. Username change
 * cooldown (05-social.md sec 1.6) reuses the existing
 * `user.username_changed_at` column: no DDL needed for it.
 */
final class Version20260925120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'In-app notification centre: the notification table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE notification (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                uuid UUID NOT NULL,
                user_id UUID NOT NULL,
                type VARCHAR(32) NOT NULL,
                subject VARCHAR(64) DEFAULT NULL,
                payload JSON NOT NULL,
                read_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_notification_uuid ON notification (uuid)');
        $this->addSql('CREATE INDEX idx_notification_inbox ON notification (user_id, read_at, created_at)');
        $this->addSql('CREATE INDEX idx_notification_subject ON notification (user_id, subject)');
        $this->addSql(<<<'SQL'
            ALTER TABLE notification ADD CONSTRAINT fk_notification_user
                FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE notification');
    }
}
