<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 5 (06-rating.md sec 5.3, 01-domain-model.md sec 6.5): the
 * `user_rating` table. Column set/names verified against `UserRating`'s
 * mapping (`doctrine:schema:validate` reports the mapping clean). No
 * backfill - rows are created lazily on a user's first rated game per
 * category; a user with no row reads as 1500/350/0.06 transiently.
 */
final class Version20260728201750 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Phase 5 (06-rating.md sec 5.3): the user_rating table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE user_rating (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id UUID NOT NULL,
                category SMALLINT NOT NULL,
                rating DOUBLE PRECISION NOT NULL DEFAULT 1500,
                deviation DOUBLE PRECISION NOT NULL DEFAULT 350,
                volatility DOUBLE PRECISION NOT NULL DEFAULT 0.06,
                games_played INT NOT NULL DEFAULT 0,
                last_rated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_rating_user_category ON user_rating (user_id, category)');
        $this->addSql('CREATE INDEX idx_user_rating_leaderboard ON user_rating (category, rating DESC) WHERE games_played > 0');
        $this->addSql(<<<'SQL'
            ALTER TABLE user_rating ADD CONSTRAINT fk_user_rating_user
                FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_rating');
    }
}
