<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260728092000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'P0.2: Create game_player table, add created_by_id, drop owner_id/is_white';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE game_player (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                user_id UUID DEFAULT NULL,
                color SMALLINT NOT NULL,
                clock_ms_remaining INT DEFAULT NULL,
                rating_before INT DEFAULT NULL,
                rating_deviation_before INT DEFAULT NULL,
                rating_after INT DEFAULT NULL,
                provisional_before BOOLEAN DEFAULT NULL,
                draw_offer_declined_at_ply INT DEFAULT NULL,
                last_seen_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                hidden_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE UNIQUE INDEX uniq_game_player_game_color ON game_player (game_id, color)');
        $this->addSql('CREATE INDEX idx_game_player_user_game ON game_player (user_id, game_id)');
        $this->addSql('ALTER TABLE game_player ADD CONSTRAINT fk_game_player_game FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_player ADD CONSTRAINT fk_game_player_user FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_player ADD CONSTRAINT chk_game_player_color CHECK (color IN (0, 1))');

        $this->warn('Backfilling game_player rows from existing owner_id/is_white data...');

        $this->addSql(<<<'SQL'
            INSERT INTO game_player (game_id, user_id, color, hidden_at)
            SELECT g.id, g.owner_id, CASE WHEN g.is_white THEN 0 ELSE 1 END, g.deleted_at
            FROM game g
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO game_player (game_id, user_id, color)
            SELECT g.id, NULL, CASE WHEN g.is_white THEN 1 ELSE 0 END
            FROM game g WHERE g.opponent_type_value = 0
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO game_player (game_id, user_id, color, hidden_at)
            SELECT g.id, g.owner_id, CASE WHEN g.is_white THEN 1 ELSE 0 END, g.deleted_at
            FROM game g WHERE g.opponent_type_value = 1
        SQL);

        $this->addSql('ALTER TABLE game ADD created_by_id UUID DEFAULT NULL');
        $this->addSql("COMMENT ON COLUMN game.created_by_id IS '(DC2Type:uuid)'");
        $this->addSql('UPDATE game SET created_by_id = owner_id');
        $this->addSql('ALTER TABLE game ALTER COLUMN created_by_id SET NOT NULL');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT fk_game_created_by FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_game_created_by ON game (created_by_id)');

        $this->addSql('ALTER TABLE game DROP CONSTRAINT IF EXISTS FK_232B318C7E3C61F9');
        $this->addSql('DROP INDEX IF EXISTS IDX_232B318C7E3C61F9');
        $this->addSql('ALTER TABLE game DROP COLUMN owner_id');
        $this->addSql('ALTER TABLE game DROP COLUMN is_white');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE game ADD owner_id UUID DEFAULT NULL');
        $this->addSql("COMMENT ON COLUMN game.owner_id IS '(DC2Type:uuid)'");
        $this->addSql('ALTER TABLE game ADD is_white BOOLEAN NOT NULL DEFAULT true');

        $this->addSql(<<<'SQL'
            UPDATE game g SET owner_id = sub.user_id, is_white = (sub.color = 0)
            FROM (
                SELECT game_id, user_id, color
                FROM game_player
                WHERE user_id IS NOT NULL
                ORDER BY color ASC
            ) sub
            WHERE sub.game_id = g.id
        SQL);

        $this->addSql('ALTER TABLE game ADD CONSTRAINT fk_game_owner FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_232B318C7E3C61F9 ON game (owner_id)');

        $this->addSql('ALTER TABLE game DROP CONSTRAINT fk_game_created_by');
        $this->addSql('DROP INDEX idx_game_created_by');
        $this->addSql('ALTER TABLE game DROP COLUMN created_by_id');

        $this->addSql('DROP TABLE game_player');
    }
}
