<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 4 (05-social.md sec 3/4, 01-domain-model.md sec 6.7): the
 * `friendship` table. Column set/names verified against `Friendship`'s
 * real Doctrine mapping via `doctrine:migrations:diff` (the auto-generated
 * statements below, hand-trimmed of unrelated pre-existing schema drift
 * bundled into that diff, and of the two bare single-column FK indexes
 * Doctrine adds by default - the composite indexes below already cover an
 * equality lookup on either leading column, matching sec 6.7's canonical
 * index list exactly). The partial unique index, the two partial block
 * indexes and the not-self CHECK constraint are added by hand -
 * `migrations:diff` does not regenerate any of those (01-domain-model.md
 * sec 6.7).
 */
final class Version20260728153508 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the friendship table (05-social.md sec 3/4, 01-domain-model.md sec 6.7).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE friendship (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              status_value SMALLINT NOT NULL,
              created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
              responded_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
              requester_id UUID NOT NULL,
              addressee_id UUID NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_friendship_pair ON friendship (requester_id, addressee_id)');
        $this->addSql('CREATE INDEX idx_friendship_addressee_status ON friendship (addressee_id, status_value)');
        $this->addSql('CREATE INDEX idx_friendship_requester_status ON friendship (requester_id, status_value)');
        // sec 4.4: partial on status=3 (BLOCKED) because blocks are rare -
        // both stay near-empty and the pairing anti-join probe is index-only.
        $this->addSql('CREATE INDEX idx_friendship_block_fwd ON friendship (requester_id, addressee_id) WHERE status_value = 3');
        $this->addSql('CREATE INDEX idx_friendship_block_rev ON friendship (addressee_id, requester_id) WHERE status_value = 3');
        // F1: at most one row per *unordered* pair outside BLOCKED (status <> 3).
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_friendship_active_pair
                ON friendship (LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id))
                WHERE status_value <> 3
        SQL);
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT chk_friendship_not_self CHECK (requester_id <> addressee_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE friendship
            ADD CONSTRAINT FK_7234A45FED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE friendship
            ADD CONSTRAINT FK_7234A45F2261B4C3 FOREIGN KEY (addressee_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE friendship');
    }
}
