<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * T6 instrumentation: the analytics_event table. Append-only collection
 * only - no dashboards, no aggregation UI, nothing reads this yet.
 * `payload` is denormalised on purpose (same reasoning as `notification`).
 * `game` is a raw UUID value, not a managed relation/FK: this table is
 * written from the hottest path in the app (a move played on every ply),
 * and a managed relation would risk an accidental join or a lock on the
 * `game` row.
 */
final class Version20260928224500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'T6 instrumentation: the analytics_event table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE analytics_event (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id UUID DEFAULT NULL,
                type VARCHAR(32) NOT NULL,
                occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                game UUID DEFAULT NULL,
                payload JSON NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_analytics_event_type_occurred ON analytics_event (type, occurred_at)');
        $this->addSql('CREATE INDEX idx_analytics_event_user ON analytics_event (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE analytics_event ADD CONSTRAINT fk_analytics_event_user
                FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE analytics_event');
    }
}
